In [70]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

*Задание 1.3.1, 8x8 матрица и шахматный порядок 0, 1*

In [27]:
indices = np.indices((8, 8))

checkboard = (indices.sum(axis=0) % 2)
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

*Задание 1.3.2, 5x5 матрица от 0 до 4*

In [20]:
row = np.arange(5)

ones_columns = np.ones((5, 1), dtype=int)
result = row * ones_columns
print(result)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

*Задание 1.3.3, матрица 3х3х3*

In [25]:
random_matrix = np.random.rand(3,3,3)
print(random_matrix)

[[[0.33671821 0.72933638 0.23107911]
  [0.78615532 0.41467487 0.21425646]
  [0.69557018 0.71618012 0.24487611]]

 [[0.33739417 0.34204676 0.58804566]
  [0.08941418 0.90484157 0.49358116]
  [0.1573693  0.08665359 0.76611   ]]

 [[0.97051744 0.42273167 0.23332725]
  [0.55128198 0.21927374 0.36027128]
  [0.32503293 0.14882434 0.38725946]]]

*Задание 1.3.4*

In [33]:
matrix = np.zeros((5, 5), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

*Задание 1.3.5*

In [36]:
array = np.array([3, 4, 2, 7, 8])
print(np.sort(array)[::-1])

[8 7 4 3 2]

*Задание 1.3.6, форма, размер и размерность*

In [44]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array, '\n', array.shape, '\n',array.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 (3, 3)
 2

*Задание 2.3.1*

In [52]:
s1 = pd.Series([3, 2, 9])
s2 = pd.Series([1,9,0])
square = np.square(s1 - s2)
sum_square = square.sum()
print(np.sqrt(sum_square))

11.575836902790225

*Задание 2.3.2*

In [58]:
url = "https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/parkinsons.csv"

dataframe = pd.read_csv(url)
dataframe.head(10)

,subject,age,sex,test_time,motor_UPDRS,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,...,Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,total_UPDRS
0,1,72,0,5.6431,28.199,0.00662,0.000034,0.00401,0.00317,0.01204,...,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006,34.398
1,1,72,0,12.6660,28.447,0.00300,0.000017,0.00132,0.00150,0.00395,...,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810,34.894
2,1,72,0,19.6810,28.695,0.00481,0.000025,0.00205,0.00208,0.00616,...,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014,35.389
3,1,72,0,25.6470,28.905,0.00528,0.000027,0.00191,0.00264,0.00573,...,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277,35.810
4,1,72,0,33.6420,29.187,0.00335,0.000020,0.00093,0.00130,0.00278,...,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361,36.375
5,1,72,0,40.6520,29.435,0.00353,0.000023,0.00119,0.00159,0.00357,...,0.01006,0.01337,0.02263,0.03019,0.009438,22.946,0.53949,0.57243,0.19500,36.870
6,1,72,0,47.6490,29.682,0.00422,0.000024,0.00212,0.00221,0.00637,...,0.02376,0.02621,0.03488,0.07128,0.013260,22.506,0.49250,0.54779,0.17563,37.363
7,1,72,0,54.6400,29.928,0.00476,0.000025,0.00226,0.00259,0.00678,...,0.00979,0.01462,0.01911,0.02937,0.027969,22.929,0.47712,0.54234,0.23844,37.857
8,1,72,0,61.6690,30.177,0.00432,0.000029,0.00156,0.00207,0.00468,...,0.01774,0.02134,0.03451,0.05323,0.013381,22.078,0.51563,0.61864,0.20037,38.353
9,1,72,0,68.6880,30.424,0.00496,0.000027,0.00258,0.00253,0.00773,...,0.02030,0.01970,0.02569,0.06089,0.018021,22.606,0.50032,0.58673,0.20117,38.849

*Задание 2.3.3*

In [63]:
print(dataframe.head(2))
print(dataframe.tail(3))

   subject  age  sex  test_time  motor_UPDRS  Jitter(%)  Jitter(Abs)  \
0        1   72    0     5.6431       28.199    0.00662     0.000034
1        1   72    0    12.6660       28.447    0.00300     0.000017

   Jitter:RAP  Jitter:PPQ5  Jitter:DDP  ...  Shimmer:APQ3  Shimmer:APQ5  \
0     0.00401      0.00317     0.01204  ...       0.01438       0.01309
1     0.00132      0.00150     0.00395  ...       0.00994       0.01072

   Shimmer:APQ11  Shimmer:DDA       NHR     HNR     RPDE      DFA      PPE  \
0        0.01662      0.04314  0.014290  21.640  0.41888  0.54842  0.16006
1        0.01689      0.02982  0.011112  27.183  0.43493  0.56477  0.10810

   total_UPDRS
0       34.398
1       34.894

[2 rows x 22 columns]
      subject  age  sex  test_time  motor_UPDRS  Jitter(%)  Jitter(Abs)  \
5872       42   61    0     156.82       21.495    0.00349     0.000025
5873       42   61    0     163.73       21.007    0.00281     0.000020
5874       42   61    0     170.73       20.513    0.00282     0.000021

      Jitter:RAP  Jitter:PPQ5  Jitter:DDP  ...  Shimmer:APQ3  Shimmer:APQ5  \
5872     0.00152      0.00187     0.00456  ...       0.01371       0.01456
5873     0.00128      0.00151     0.00383  ...       0.00693       0.00870
5874     0.00135      0.00166     0.00406  ...       0.00946       0.01154

      Shimmer:APQ11  Shimmer:DDA       NHR     HNR     RPDE      DFA      PPE  \
5872        0.01877      0.04112  0.017701  25.065  0.47792  0.57888  0.14157
5873        0.01307      0.02078  0.007984  24.422  0.56865  0.56327  0.14204
5874        0.01470      0.02839  0.008172  23.259  0.58608  0.57077  0.15336

      total_UPDRS
5872       32.495
5873       32.007
5874       31.513

[3 rows x 22 columns]

In [65]:
print(dataframe.shape)

(5875, 22)

In [66]:
dataframe.describe()

,subject,age,sex,test_time,motor_UPDRS,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,...,Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,total_UPDRS
count,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,...,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000
mean,21.494128,64.804936,0.317787,92.863722,21.296229,0.006154,0.000044,0.002987,0.003277,0.008962,...,0.017156,0.020144,0.027481,0.051467,0.032120,21.679495,0.541473,0.653240,0.219589,29.018942
std,12.372279,8.821524,0.465656,53.445602,8.129282,0.005624,0.000036,0.003124,0.003732,0.009371,...,0.013237,0.016664,0.019986,0.039711,0.059692,4.291096,0.100986,0.070902,0.091498,10.700283
min,1.000000,36.000000,0.000000,-4.262500,5.037700,0.000830,0.000002,0.000330,0.000430,0.000980,...,0.001610,0.001940,0.002490,0.004840,0.000286,1.659000,0.151020,0.514040,0.021983,7.000000
25%,10.000000,58.000000,0.000000,46.847500,15.000000,0.003580,0.000022,0.001580,0.001820,0.004730,...,0.009280,0.010790,0.015665,0.027830,0.010955,19.406000,0.469785,0.596180,0.156340,21.371000
50%,22.000000,65.000000,0.000000,91.523000,20.871000,0.004900,0.000034,0.002250,0.002490,0.006750,...,0.013700,0.015940,0.022710,0.041110,0.018448,21.920000,0.542250,0.643600,0.205500,27.576000
75%,33.000000,72.000000,1.000000,138.445000,27.596500,0.006800,0.000053,0.003290,0.003460,0.009870,...,0.020575,0.023755,0.032715,0.061735,0.031463,24.444000,0.614045,0.711335,0.264490,36.399000
max,42.000000,85.000000,1.000000,215.490000,39.511000,0.099990,0.000446,0.057540,0.069560,0.172630,...,0.162670,0.167020,0.275460,0.488020,0.748260,37.875000,0.966080,0.865600,0.731730,54.992000

In [67]:
dataframe.iloc[3000:3002]

,subject,age,sex,test_time,motor_UPDRS,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,...,Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,total_UPDRS
3000,22,57,1,159.87,12.356,0.00218,0.000009,0.00113,0.00121,0.00339,...,0.00765,0.00910,0.01297,0.02296,0.001522,29.627,0.44540,0.65075,0.10806,14.652
3001,22,57,1,165.88,12.824,0.00209,0.000009,0.00111,0.00114,0.00332,...,0.00818,0.00944,0.01139,0.02455,0.002026,27.360,0.31297,0.67408,0.10312,15.320

In [69]:
dataframe[dataframe['subject'] == 15].head(3)

,subject,age,sex,test_time,motor_UPDRS,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,...,Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,total_UPDRS
1991,15,65,0,26.473,9.3273,0.00508,0.000036,0.00259,0.00266,0.00778,...,0.01836,0.02056,0.02792,0.05507,0.018587,22.511,0.49420,0.71232,0.20795,13.618
1992,15,65,0,33.506,9.9456,0.00377,0.000025,0.00185,0.00197,0.00555,...,0.02821,0.03420,0.04834,0.08462,0.018216,20.825,0.67209,0.67492,0.15013,14.314
1993,15,65,0,40.481,10.5590,0.00412,0.000031,0.00218,0.00209,0.00654,...,0.03168,0.03063,0.04635,0.09505,0.013071,21.083,0.65937,0.70809,0.18250,15.004

*Задание 3.3.2*

In [81]:
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"

dataframe = pd.read_csv(url)
minimax_scale = preprocessing.MinMaxScaler()
z_scaler = preprocessing.StandardScaler()

dataframe[['sepal_length_cm']] = minimax_scale.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = z_scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe.head(5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa